### ISSUE TITLE
Moflex with odd framerate won't convert

### ISSUE THREAD

**Issue by redunka-zver** [adibsurani/Mobius#2]
Mobius errors out on some videos, saying that it can't set framerate for them.
Those have fractional framerates, i.e. not just "30" or "60", but "23.976023976024" or "59.9400599400599".
Can something be done about this, or is that ffmpeg's issue?

**Comment by AdibSurani** [comment]
This should be fixed in the latest release, the issue being that you're using a locale that encodes decimal points as commas. Let me know if the new update works for you.

**Comment by redunka-zver** [comment]
Oh, I'm sorry that I didn't reply sooner, I totally missed that there was a new release.
Indeed, those videos are converting properly now, and even with sound, that's amazing!
Thank you very much!

By the way, you may already know about this, but I thought I may as well mention it.
I've noticed that some videos that have sound may not convert anymore, even if they did before.
They give something about "sequence contains more than one element".
As far as I remember, those moflex files have more than one audio track, so maybe that's the reason.
Well, since this is unrelated to the above problem, I can always create another issue if needed, while this one can be closed as resolved.

I'm sorry for bothering you this much, and thank you for this awesome tool again!
